### ISSUE TITLE
Issue when header does not contain any scripts

### ISSUE THREAD

**Issue by sidati** [nodecode/wp-minify-fix#8]
Hello,

First of all thank you for this "finally" good minifier.
secondly, in the line 892 (wp-minify.php), there is an if condition for checking of $js_locations, which contains only Header scripts, but if header has no scripts like in my theme, it will not include JS minified file even if theres is one generated by wp-minify-fix from the footer scripts.

So, please replace this line 892 in wp-minify.php

``` php
if (count($js_locations) > 0) {
```

with

``` php
if (count($js_locations) > 0 || count($js_locations_footer) > 0) {
```

Best,
Sidati

**Comment by nodecode** [comment]
Hi,

This issue has already been fixed in the current master branch and will be released in the next version.

**Comment by sidati** [comment]
Cool :),
Keep up the good work
